openapi: 3.1.0
info:
  title: bucket-api
  version: '1.0'
  summary: CRUD gcs bucket
  description: CRUD gcs bucket
servers:
  - url: 'http://localhost:3000'
paths:
  '/copy{bucket_path}':
    parameters:
      - schema:
          type: string
        name: bucket_path
        in: path
        required: true
    get:
      summary: Copy
      tags:
        - path
      responses:
        '200':
          description: OK
        '201':
          description: Created
        '400':
          description: Bad Request
      operationId: get-copy-bucket_path
  '/Delete{path}':
    get:
      summary: Del
      tags: []
      responses:
        '200':
          description: OK
        '201':
          description: Created
        '400':
          description: Bad Request
      operationId: get-Delete
    parameters:
      - schema:
          type: string
        name: path
        in: path
        required: true
  /list:
    get:
      summary: LIST
      tags: []
      responses:
        '200':
          description: OK
        '201':
          description: Created
        '400':
          description: Bad Request
      operationId: get-list
components:
  schemas: {}
