openapi: 3.0.0
info:
  title: bucket-gcpcopyv1
  version: "1.0"
servers:
- url: http://localhost:3000
paths:
  /users/{userId}: {}
  /user: {}
  /copy:
    get:
      tags: []
      summary: path
      operationId: get_copy_path
      parameters:
      - name: copy
        in: query
        required: false
        style: form
        explode: true
        schema:
          type: string
      responses:
        "200":
          description: OK
        "201":
          description: Created
        "400":
          description: Bad Request
      x-openapi-router-controller: swagger_server.controllers.default_controller
  /delete:
    get:
      tags:
      - Delete
      summary: Delete
      operationId: get_delete_path
      parameters:
      - name: query
        in: query
        required: false
        style: form
        explode: true
        schema:
          type: string
      responses:
        "200":
          description: OK
        "201":
          description: Created
        "400":
          description: Bad Request
      x-openapi-router-controller: swagger_server.controllers.delete_controller
  /list:
    get:
      tags: []
      summary: list
      operationId: get_list_path
      parameters:
      - name: query
        in: query
        required: false
        style: form
        explode: true
        schema:
          type: string
      responses:
        "200":
          description: OK
        "201":
          description: Created
        "400":
          description: Bad Request
      x-openapi-router-controller: swagger_server.controllers.default_controller
components:
  schemas: {}

